### Default ###
spring:
  application:
    name: heredraw

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  profiles:
    active: local
   
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
